import { useEffect,useRef,useState } from "react";
import { useLocalSearchParams,useRouter } from "expo-router";
import { SafeAreaView,KeyboardAvoidingView,Platform,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View } from "react-native";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
import { colors,radii } from "../../src/theme";
type Msg={id:string;sender_id:string;body:string;created_at:string;conversation_id:string};
export default function ChatScreen(){const {conversationId}=useLocalSearchParams<{conversationId:string}>();const router=useRouter();const {userId}=useAuth();const [messages,setMessages]=useState<Msg[]>([]);const [body,setBody]=useState("");const scroll=useRef<ScrollView>(null);useEffect(()=>{if(!conversationId||!userId)return;void supabase.from("messages").select("id,sender_id,body,created_at,conversation_id").eq("conversation_id",conversationId).order("created_at").then(({data})=>setMessages((data||[]) as Msg[]));const ch=supabase.channel(`mobile-chat:${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},p=>{const m=p.new as Msg;setMessages(old=>old.some(x=>x.id===m.id)?old:[...old,m])}).subscribe();return()=>{void supabase.removeChannel(ch)}},[conversationId,userId]);async function send(){const text=body.trim();if(!text||!userId)return;setBody("");const {error}=await supabase.from("messages").insert({conversation_id:conversationId,sender_id:userId,body:text});if(error)setBody(text)}return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><View style={s.top}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>←</Text></TouchableOpacity><View><Text style={s.title}>Cakelio chat</Text><Text style={s.sub}>Cake request conversation</Text></View><View style={{width:30}}/></View><ScrollView ref={scroll} onContentSizeChange={()=>scroll.current?.scrollToEnd({animated:true})} contentContainerStyle={s.messages}>{messages.length===0?<Text style={s.empty}>No messages yet. Say hello and discuss the cake details.</Text>:messages.map(m=><View key={m.id} style={[s.bubble,m.sender_id===userId?s.mine:s.theirs]}><Text style={m.sender_id===userId?s.mineText:s.theirText}>{m.body}</Text><Text style={[s.time,m.sender_id===userId&&{color:"#CDBEB7"}]}>{new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</Text></View>)}</ScrollView><View style={s.composer}><TextInput style={s.input} value={body} onChangeText={setBody} placeholder="Write a message…" placeholderTextColor={colors.muted}/><TouchableOpacity style={s.send} onPress={()=>void send()}><Text style={s.sendText}>Send</Text></TouchableOpacity></View></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},top:{height:66,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderColor:colors.line},back:{fontSize:24,color:colors.terra},title:{fontSize:14,fontWeight:"800",color:colors.cocoa,textAlign:"center"},sub:{fontSize:9,color:colors.muted,textAlign:"center"},messages:{padding:16,gap:8,flexGrow:1},empty:{padding:18,color:colors.muted,textAlign:"center"},bubble:{maxWidth:"80%",padding:11,borderRadius:16},mine:{alignSelf:"flex-end",backgroundColor:colors.cocoa},theirs:{alignSelf:"flex-start",backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line},mineText:{color:colors.cream,lineHeight:20},theirText:{color:colors.cocoa,lineHeight:20},time:{fontSize:8,color:colors.muted,marginTop:4},composer:{padding:10,borderTopWidth:1,borderColor:colors.line,flexDirection:"row",gap:8,backgroundColor:colors.paper},input:{flex:1,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:14,color:colors.cocoa,backgroundColor:colors.cream},send:{backgroundColor:colors.terra,borderRadius:radii.pill,paddingHorizontal:16,justifyContent:"center"},sendText:{color:colors.white,fontWeight:"800"}})
