import { useMemo, useState } from "react";
import { useRouter } from "expo-router";
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { CakePreview } from "../src/components/CakePreview";
import { colors, radii } from "../src/theme";
const sizes=[{label:"15 cm",add:0,serves:"6–8"},{label:"20 cm",add:14,serves:"12–16"},{label:"25 cm",add:29,serves:"20–24"}];
const flavours=[{label:"Vanilla",add:0},{label:"Chocolate",add:5},{label:"Red velvet",add:7},{label:"Lemon",add:4}];
const decorations=[{label:"Minimal",add:0},{label:"Berries",add:7},{label:"Flowers",add:13},{label:"Gold",add:10}];
export default function StudioScreen(){const router=useRouter();const [size,setSize]=useState(sizes[1]);const [flavour,setFlavour]=useState(flavours[1]);const [frosting,setFrosting]=useState("Blush");const [decoration,setDecoration]=useState(decorations[2]);const [tiers,setTiers]=useState(1);const [message,setMessage]=useState("happy birthday");const estimate=useMemo(()=>42+size.add+flavour.add+decoration.add+(tiers-1)*24,[size,flavour,decoration,tiers]);return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><View style={styles.top}><TouchableOpacity onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>←</Text></TouchableOpacity><View><Text style={styles.topTitle}>Cakelio Studio</Text><Text style={styles.topSub}>Interactive prototype</Text></View><TouchableOpacity><Text style={styles.save}>♡ Save</Text></TouchableOpacity></View><CakePreview frosting={frosting} tiers={tiers} message={message} decoration={decoration.label}/><View style={styles.estimate}><View><Text style={styles.estimateLabel}>EARLY ESTIMATE</Text><Text style={styles.estimatePrice}>€{estimate}–€{estimate+18}</Text></View><Text style={styles.estimateNote}>Final price is set by your baker.</Text></View><Control title="Size" subtitle={`${size.serves} servings`} options={sizes.map(x=>x.label)} value={size.label} onChange={v=>setSize(sizes.find(x=>x.label===v)!)} /><Control title="Cake flavour" options={flavours.map(x=>x.label)} value={flavour.label} onChange={v=>setFlavour(flavours.find(x=>x.label===v)!)} /><Control title="Finish colour" options={["Vanilla","Blush","Sage","Chocolate","Lemon"]} value={frosting} onChange={setFrosting}/><Control title="Decoration" options={decorations.map(x=>x.label)} value={decoration.label} onChange={v=>setDecoration(decorations.find(x=>x.label===v)!)} /><View style={styles.group}><View style={styles.labelRow}><Text style={styles.label}>Tiers</Text><Text style={styles.subLabel}>Baker limits come later</Text></View><View style={styles.choices}>{[1,2].map(x=><TouchableOpacity key={x} style={[styles.choice,tiers===x&&styles.choiceActive]} onPress={()=>setTiers(x)}><Text style={[styles.choiceText,tiers===x&&styles.choiceTextActive]}>{x}</Text></TouchableOpacity>)}</View></View><View style={styles.group}><View style={styles.labelRow}><Text style={styles.label}>Cake message</Text><Text style={styles.subLabel}>{message.length}/28</Text></View><TextInput value={message} onChangeText={setMessage} maxLength={28} style={styles.input}/></View><TouchableOpacity style={styles.cta} onPress={()=>router.replace("/(tabs)/bakers")}><Text style={styles.ctaText}>Find bakers for this cake</Text></TouchableOpacity></ScrollView></SafeAreaView>}
function Control({title,subtitle,options,value,onChange}:{title:string;subtitle?:string;options:string[];value:string;onChange:(v:string)=>void}){return <View style={styles.group}><View style={styles.labelRow}><Text style={styles.label}>{title}</Text>{subtitle&&<Text style={styles.subLabel}>{subtitle}</Text>}</View><View style={styles.choices}>{options.map(o=><TouchableOpacity key={o} style={[styles.choice,value===o&&styles.choiceActive]} onPress={()=>onChange(o)}><Text style={[styles.choiceText,value===o&&styles.choiceTextActive]}>{o}</Text></TouchableOpacity>)}</View></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{paddingHorizontal:16,paddingBottom:40},top:{height:72,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:36,height:36,borderRadius:18,borderWidth:1,borderColor:colors.line,alignItems:"center",justifyContent:"center"},backText:{fontSize:18,color:colors.cocoa},topTitle:{fontSize:15,fontWeight:"800",color:colors.cocoa,textAlign:"center"},topSub:{fontSize:9,color:colors.muted,textAlign:"center",marginTop:2},save:{fontSize:11,fontWeight:"800",color:colors.terra},estimate:{marginTop:12,backgroundColor:colors.cocoa,borderRadius:radii.medium,padding:16,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},estimateLabel:{fontSize:8,letterSpacing:1.2,fontWeight:"800",color:"#C8D3C6"},estimatePrice:{fontSize:24,fontFamily:"serif",color:colors.cream,marginTop:2},estimateNote:{fontSize:9,lineHeight:13,color:"#C8BAB2",maxWidth:110,textAlign:"right"},group:{paddingVertical:18,borderBottomWidth:1,borderColor:colors.line},labelRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:10},label:{fontSize:13,fontWeight:"800",color:colors.cocoa},subLabel:{fontSize:9,color:colors.muted},choices:{flexDirection:"row",flexWrap:"wrap",gap:7},choice:{minWidth:"47%",flexGrow:1,borderWidth:1,borderColor:colors.line,backgroundColor:colors.paper,borderRadius:12,paddingHorizontal:12,paddingVertical:11,alignItems:"center"},choiceActive:{borderColor:colors.sage,backgroundColor:colors.sageSoft},choiceText:{fontSize:10,color:colors.cocoa2},choiceTextActive:{fontWeight:"800",color:"#334735"},input:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12,color:colors.cocoa},cta:{marginTop:24,backgroundColor:colors.terra,borderRadius:radii.pill,padding:16,alignItems:"center"},ctaText:{color:colors.white,fontWeight:"800",fontSize:12}})
