import { useEffect,useState } from "react";
import { useRouter } from "expo-router";
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Logo } from "../../src/components/Logo";
import { supabase } from "../../src/lib/supabase";
import { colors, radii } from "../../src/theme";

type Baker={user_id:string;business_name:string;city:string|null;postal_code:string|null;starting_price:number|null;currency:string;minimum_lead_days:number;delivery_radius_km:number|null;is_verified:boolean};
export default function BakersScreen(){const router=useRouter();const [bakers,setBakers]=useState<Baker[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{void supabase.from("provider_profiles").select("user_id,business_name,city,postal_code,starting_price,currency,minimum_lead_days,delivery_radius_km,is_verified").eq("status","active").eq("is_discoverable",true).eq("accepting_orders",true).order("created_at",{ascending:false}).then(({data})=>{setBakers((data||[]) as Baker[]);setLoading(false)})},[]);return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><View style={styles.nav}><Logo/></View><Text style={styles.kicker}>CAKELIO MARKET</Text><Text style={styles.title}>Find the right baker.</Text><Text style={styles.lead}>Real bakery profiles, connected to the same Cakelio backend as the website.</Text>{loading?<Text style={styles.empty}>Loading bakers…</Text>:bakers.length===0?<Text style={styles.empty}>No active baker profiles yet. Providers can publish from their profile.</Text>:bakers.map((b,i)=><View style={styles.card} key={b.user_id}><View style={[styles.photo,{backgroundColor:[colors.sageSoft,colors.terraSoft,colors.butter][i%3]}]}><Text style={styles.initials}>{b.business_name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</Text>{b.is_verified&&<Text style={styles.verified}>✓ Verified</Text>}</View><View style={styles.body}><Text style={styles.name}>{b.business_name}</Text><Text style={styles.city}>{[b.city,b.postal_code].filter(Boolean).join(" · ")||"Germany"}</Text><View style={styles.tags}><Text style={styles.tag}>{b.minimum_lead_days}d lead time</Text>{b.delivery_radius_km!=null&&<Text style={styles.tag}>{b.delivery_radius_km} km delivery</Text>}</View><View style={styles.bottom}><Text style={styles.price}>{b.starting_price!=null?`From €${Number(b.starting_price).toFixed(0)}`:"Request quote"}</Text><TouchableOpacity onPress={()=>router.push(`/order/${b.user_id}`)}><Text style={styles.request}>Order →</Text></TouchableOpacity></View></View></View>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{paddingHorizontal:18,paddingBottom:38},nav:{height:68,justifyContent:"center"},kicker:{marginTop:25,color:colors.sage,fontSize:10,fontWeight:"800",letterSpacing:1.5},title:{fontSize:39,lineHeight:42,fontWeight:"700",letterSpacing:-1.8,color:colors.cocoa,marginTop:7},lead:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8,marginBottom:18},empty:{padding:24,backgroundColor:colors.paper,borderRadius:radii.medium,color:colors.muted,lineHeight:20},card:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radii.large,overflow:"hidden",marginBottom:13},photo:{height:150,alignItems:"center",justifyContent:"center"},initials:{width:60,height:60,borderRadius:20,backgroundColor:"rgba(255,255,255,.72)",textAlign:"center",textAlignVertical:"center",fontFamily:"serif",fontSize:20,color:colors.cocoa},verified:{position:"absolute",top:12,left:12,fontSize:9,fontWeight:"800",backgroundColor:colors.paper,paddingHorizontal:8,paddingVertical:5,borderRadius:99,color:colors.sage},body:{padding:16},name:{fontSize:17,fontWeight:"800",color:colors.cocoa},city:{fontSize:10,color:colors.muted,marginTop:3},tags:{flexDirection:"row",gap:5,flexWrap:"wrap",marginVertical:14},tag:{fontSize:9,color:colors.cocoa2,backgroundColor:colors.cream2,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:8,paddingVertical:5},bottom:{borderTopWidth:1,borderColor:colors.line,paddingTop:12,flexDirection:"row",justifyContent:"space-between"},price:{fontSize:11,fontWeight:"700",color:colors.cocoa},request:{fontSize:11,fontWeight:"800",color:colors.terra}})
