import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Logo } from "../../src/components/Logo";
import { colors, radii } from "../../src/theme";
const bakers=[
{name:"Mila Cake Atelier",city:"Frankfurt-Sachsenhausen",rating:"4.9",price:"From €58",tags:["Buttercream","Wedding","Floral"],bg:"#DFE7DD"},
{name:"Studio Zucker",city:"Offenbach",rating:"4.8",price:"From €65",tags:["Fondant","Birthday","Sculpted"],bg:"#F1D2C7"},
{name:"Little Whisk",city:"Frankfurt-Bornheim",rating:"5.0",price:"From €52",tags:["Vegan","Minimal","Celebration"],bg:"#F6E4B5"},
{name:"Crumb & Bloom",city:"Frankfurt-Westend",rating:"4.9",price:"From €70",tags:["Wedding","Modern","Flowers"],bg:"#E3D6CD"}
];
export default function BakersScreen(){return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><View style={styles.nav}><Logo/><View/></View><Text style={styles.kicker}>CAKELIO MARKET</Text><Text style={styles.title}>Find the right baker.</Text><Text style={styles.lead}>Later this list will be matched to your design, date and delivery area.</Text><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><TextInput style={styles.searchInput} defaultValue="Frankfurt am Main"/><TouchableOpacity style={styles.searchButton}><Text style={styles.searchButtonText}>Search</Text></TouchableOpacity></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><Text style={styles.filter}>Available date</Text><Text style={styles.filter}>Cake style</Text><Text style={styles.filter}>Dietary</Text><Text style={styles.filter}>Price</Text></ScrollView>{bakers.map(b=><View style={styles.card} key={b.name}><View style={[styles.photo,{backgroundColor:b.bg}]}><Text style={styles.initials}>{b.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</Text><TouchableOpacity style={styles.heart}><Text>♡</Text></TouchableOpacity></View><View style={styles.body}><View style={styles.row}><View style={{flex:1}}><Text style={styles.name}>{b.name}</Text><Text style={styles.city}>{b.city}</Text></View><Text style={styles.rating}>★ {b.rating}</Text></View><View style={styles.tags}>{b.tags.map(t=><Text style={styles.tag} key={t}>{t}</Text>)}</View><View style={styles.bottom}><Text style={styles.price}>{b.price}</Text><Text style={styles.request}>View & request →</Text></View></View></View>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{paddingHorizontal:18,paddingBottom:38},nav:{height:68,justifyContent:"center"},kicker:{marginTop:25,color:colors.sage,fontSize:10,fontWeight:"800",letterSpacing:1.5},title:{fontSize:39,lineHeight:42,fontWeight:"750",letterSpacing:-1.8,color:colors.cocoa,marginTop:7},lead:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8},search:{flexDirection:"row",alignItems:"center",backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:15,padding:6,paddingLeft:12,marginTop:22},searchIcon:{fontSize:18,color:colors.muted},searchInput:{flex:1,paddingHorizontal:8,color:colors.cocoa},searchButton:{backgroundColor:colors.cocoa,borderRadius:11,paddingHorizontal:14,paddingVertical:10},searchButtonText:{color:colors.cream,fontWeight:"800",fontSize:11},filters:{gap:7,paddingVertical:15},filter:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:12,paddingVertical:8,fontSize:10,color:colors.cocoa2},card:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radii.large,overflow:"hidden",marginBottom:13},photo:{height:190,alignItems:"center",justifyContent:"center"},initials:{width:60,height:60,borderRadius:20,backgroundColor:"rgba(255,255,255,.72)",textAlign:"center",textAlignVertical:"center",fontFamily:"serif",fontSize:20,color:colors.cocoa},heart:{position:"absolute",right:14,top:14,width:34,height:34,borderRadius:17,backgroundColor:"rgba(255,255,255,.82)",alignItems:"center",justifyContent:"center"},body:{padding:16},row:{flexDirection:"row",gap:10},name:{fontSize:17,fontWeight:"800",color:colors.cocoa},city:{fontSize:10,color:colors.muted,marginTop:3},rating:{fontSize:11,fontWeight:"700",color:colors.cocoa},tags:{flexDirection:"row",gap:5,flexWrap:"wrap",marginVertical:14},tag:{fontSize:9,color:colors.cocoa2,backgroundColor:colors.cream2,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:8,paddingVertical:5},bottom:{borderTopWidth:1,borderColor:colors.line,paddingTop:12,flexDirection:"row",justifyContent:"space-between"},price:{fontSize:11,fontWeight:"700",color:colors.cocoa},request:{fontSize:11,fontWeight:"800",color:colors.terra}})
