import { useEffect,useState } from "react";
import { useRouter } from "expo-router";
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Logo } from "../../src/components/Logo";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
import { colors, radii } from "../../src/theme";
type Conversation={id:string;request_id:string;created_at:string};
export default function InboxScreen(){const router=useRouter();const {userId,profile}=useAuth();const [rows,setRows]=useState<Conversation[]>([]);useEffect(()=>{if(!userId){setRows([]);return}const field=profile?.primary_role==="provider"?"provider_id":"customer_id";void supabase.from("conversations").select("id,request_id,created_at").eq(field,userId).order("created_at",{ascending:false}).then(({data})=>setRows((data||[]) as Conversation[]))},[userId,profile?.primary_role]);if(!userId)return <SafeAreaView style={styles.safe}><View style={styles.page}><View style={styles.nav}><Logo/></View><Text style={styles.kicker}>CONVERSATIONS</Text><Text style={styles.title}>Your cake chats.</Text><Text style={styles.empty}>Sign in to message bakers and customers.</Text><TouchableOpacity style={styles.button} onPress={()=>router.push("/auth")}><Text style={styles.buttonText}>Sign in</Text></TouchableOpacity></View></SafeAreaView>;return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.nav}><Logo/></View><Text style={styles.kicker}>CONVERSATIONS</Text><Text style={styles.title}>Your cake chats.</Text>{rows.length===0?<Text style={styles.empty}>When a customer sends a cake request, its private conversation appears here automatically.</Text>:rows.map(r=><TouchableOpacity key={r.id} style={styles.card} onPress={()=>router.push(`/chat/${r.id}`)}><View><Text style={styles.cardTitle}>{profile?.primary_role==="provider"?"Customer cake request":"Baker conversation"}</Text><Text style={styles.meta}>Request {r.request_id.slice(0,8)}</Text></View><Text style={styles.arrow}>→</Text></TouchableOpacity>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{paddingHorizontal:18,paddingBottom:40},nav:{height:68,justifyContent:"center"},kicker:{marginTop:25,color:colors.sage,fontSize:10,fontWeight:"800",letterSpacing:1.5},title:{fontSize:39,fontWeight:"700",letterSpacing:-1.8,color:colors.cocoa,marginTop:7,marginBottom:18},empty:{padding:22,backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,color:colors.muted,lineHeight:20},button:{marginTop:14,backgroundColor:colors.terra,borderRadius:radii.pill,padding:13,alignItems:"center"},buttonText:{color:colors.white,fontWeight:"800"},card:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,padding:17,marginBottom:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},cardTitle:{fontSize:14,fontWeight:"800",color:colors.cocoa},meta:{fontSize:10,color:colors.muted,marginTop:4},arrow:{fontSize:20,color:colors.terra}})
