import { useRouter } from "expo-router";
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { CakePreview } from "../../src/components/CakePreview";
import { Logo } from "../../src/components/Logo";
import { useAuth } from "../../src/context/AuthContext";
import { colors, radii } from "../../src/theme";

const makers=[{name:"Mila Cake Atelier",meta:"Frankfurt · ★ 4.9",color:"#DFE7DD"},{name:"Studio Zucker",meta:"Offenbach · ★ 4.8",color:"#F1D2C7"},{name:"Little Whisk",meta:"Frankfurt · ★ 5.0",color:"#F6E4B5"}];

export default function HomeScreen(){
  const router=useRouter();
  const {userId}=useAuth();
  return <SafeAreaView style={styles.safe}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.page}>
    <View style={styles.nav}><Logo/><TouchableOpacity style={styles.signIn} onPress={()=>router.push(userId?"/(tabs)/profile":"/auth")}><Text style={styles.signInText}>{userId?"Account":"Sign in"}</Text></TouchableOpacity></View>
    <View style={styles.hero}><Text style={styles.eyebrow}>CUSTOM CAKES, WITHOUT THE CHAOS</Text><Text style={styles.title}>Imagine it.\nShape it.\n<Text style={styles.accent}>Make it real.</Text></Text><Text style={styles.lead}>Create a clear cake design, discover a baker who can make it and keep the whole order in one place.</Text><TouchableOpacity style={styles.primary} onPress={()=>router.push("/studio")}><Text style={styles.primaryText}>Start designing</Text></TouchableOpacity></View>
    <View style={styles.previewCard}><View style={styles.previewHead}><Text style={styles.previewTitle}>Cakelio Studio</Text><Text style={styles.live}>LIVE PREVIEW</Text></View><CakePreview/><View style={styles.tags}><Text style={styles.tag}>20 cm</Text><Text style={styles.tag}>Chocolate</Text><Text style={styles.tag}>Floral</Text></View></View>
    <View style={styles.sectionHead}><View><Text style={styles.kicker}>NEAR YOU</Text><Text style={styles.sectionTitle}>Cake makers to explore</Text></View><TouchableOpacity onPress={()=>router.push("/(tabs)/bakers")}><Text style={styles.link}>See all</Text></TouchableOpacity></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.makers}>{makers.map(m=><View style={styles.makerCard} key={m.name}><View style={[styles.makerPhoto,{backgroundColor:m.color}]}><Text style={styles.makerInitial}>{m.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</Text></View><Text style={styles.makerName}>{m.name}</Text><Text style={styles.makerMeta}>{m.meta}</Text></View>)}</ScrollView>
    <View style={styles.proCard}><Text style={styles.proKicker}>CAKELIO PRO</Text><Text style={styles.proTitle}>Are you a cake maker?</Text><Text style={styles.proText}>Receive structured requests, manage quotes and show customers exactly what you can create.</Text><TouchableOpacity style={styles.proButton} onPress={()=>router.push("/(tabs)/profile")}><Text style={styles.proButtonText}>Explore provider mode</Text></TouchableOpacity></View>
  </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{paddingHorizontal:18,paddingBottom:40},nav:{height:68,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},signIn:{borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:15,paddingVertical:9},signInText:{color:colors.cocoa,fontSize:12,fontWeight:"700"},hero:{paddingTop:38,paddingBottom:26},eyebrow:{color:colors.sage,fontSize:10,fontWeight:"800",letterSpacing:1.5,marginBottom:14},title:{fontSize:49,lineHeight:48,fontWeight:"700",letterSpacing:-2.2,color:colors.cocoa},accent:{color:colors.terra},lead:{fontSize:15,lineHeight:23,color:colors.muted,marginTop:18,marginBottom:23},primary:{backgroundColor:colors.terra,borderRadius:radii.pill,padding:16,alignItems:"center"},primaryText:{color:colors.white,fontWeight:"800"},previewCard:{backgroundColor:colors.paper,borderRadius:radii.large,borderWidth:1,borderColor:colors.line,padding:14},previewHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",padding:4,marginBottom:10},previewTitle:{fontWeight:"800",color:colors.cocoa},live:{fontSize:9,fontWeight:"800",letterSpacing:1,color:colors.sage},tags:{flexDirection:"row",gap:6,flexWrap:"wrap",paddingTop:10},tag:{backgroundColor:colors.cream2,borderWidth:1,borderColor:colors.line,borderRadius:radii.pill,paddingHorizontal:9,paddingVertical:6,fontSize:10,color:colors.cocoa2},sectionHead:{marginTop:38,marginBottom:14,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between"},kicker:{fontSize:9,fontWeight:"800",letterSpacing:1.4,color:colors.sage},sectionTitle:{fontSize:25,fontWeight:"700",letterSpacing:-1,color:colors.cocoa,marginTop:5},link:{color:colors.terra,fontWeight:"800",fontSize:12},makers:{gap:10,paddingRight:18},makerCard:{width:190,backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radii.medium,padding:10},makerPhoto:{height:120,borderRadius:14,alignItems:"center",justifyContent:"center"},makerInitial:{width:50,height:50,borderRadius:16,backgroundColor:"rgba(255,255,255,.72)",textAlign:"center",textAlignVertical:"center",fontFamily:"serif",fontSize:18,color:colors.cocoa},makerName:{fontSize:13,fontWeight:"800",color:colors.cocoa,marginTop:10},makerMeta:{fontSize:10,color:colors.muted,marginTop:3},proCard:{backgroundColor:colors.cocoa,borderRadius:radii.large,padding:24,marginTop:36},proKicker:{fontSize:9,letterSpacing:1.5,fontWeight:"800",color:"#C8D3C6"},proTitle:{fontSize:27,fontWeight:"700",letterSpacing:-1,color:colors.cream,marginTop:8},proText:{fontSize:13,lineHeight:20,color:"#D2C6BE",marginTop:9},proButton:{alignSelf:"flex-start",marginTop:18,backgroundColor:colors.cream,borderRadius:radii.pill,paddingHorizontal:16,paddingVertical:11},proButtonText:{color:colors.cocoa,fontWeight:"800",fontSize:11}})
