import { useEffect,useState } from "react";
import { useLocalSearchParams,useRouter } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View } from "react-native";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
import { colors,radii } from "../../src/theme";
export default function OrderScreen(){const {providerId}=useLocalSearchParams<{providerId:string}>();const router=useRouter();const {userId}=useAuth();const [baker,setBaker]=useState<any>(null);const [date,setDate]=useState("");const [budget,setBudget]=useState("");const [notes,setNotes]=useState("");const [city,setCity]=useState("");const [design,setDesign]=useState<Record<string,unknown>>({});const [status,setStatus]=useState("");useEffect(()=>{if(providerId)void supabase.from("provider_profiles").select("user_id,business_name,minimum_lead_days,city").eq("user_id",providerId).maybeSingle().then(({data})=>setBaker(data));void AsyncStorage.getItem("cakelio-studio-draft").then(raw=>{if(raw)try{setDesign(JSON.parse(raw))}catch{}})},[providerId]);if(!userId)return <SafeAreaView style={s.safe}><View style={s.page}><Text style={s.title}>Sign in to order</Text><TouchableOpacity style={s.primary} onPress={()=>router.push("/auth")}><Text style={s.primaryText}>Sign in</Text></TouchableOpacity></View></SafeAreaView>;async function submit(){if(!date)return setStatus("Choose an event date.");const {data,error}=await supabase.rpc("submit_order_request",{p_provider_id:providerId,p_design_name:"Mobile cake design",p_design_config:design,p_event_date:date,p_fulfillment_type:city?"delivery":"pickup",p_delivery_city:city||null,p_delivery_postal_code:null,p_budget_min:null,p_budget_max:budget?Number(budget):null,p_notes:notes||null});if(error)return setStatus(error.message);const result=data as {conversation_id?:string};if(result?.conversation_id)router.replace(`/chat/${result.conversation_id}`);else setStatus("Request sent.")}return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>← Back</Text></TouchableOpacity><Text style={s.kicker}>PLACE A CAKE ORDER</Text><Text style={s.title}>{baker?`Order from ${baker.business_name}`:"Cake order"}</Text><Text style={s.body}>The baker reviews your design and sends the final quote before payment.</Text><Label text="Event date"/><TextInput style={s.input} placeholder="YYYY-MM-DD" placeholderTextColor={colors.muted} value={date} onChangeText={setDate}/><Label text="Maximum budget €"/><TextInput style={s.input} keyboardType="decimal-pad" value={budget} onChangeText={setBudget}/><Label text="Delivery city (leave empty for pickup)"/><TextInput style={s.input} value={city} onChangeText={setCity}/><Label text="Message to baker"/><TextInput style={[s.input,{minHeight:100,textAlignVertical:"top"}]} multiline value={notes} onChangeText={setNotes}/>{Object.keys(design).length>0?<Text style={s.notice}>✓ Your latest Cakelio Studio design is attached.</Text>:null}<TouchableOpacity style={s.primary} onPress={()=>void submit()}><Text style={s.primaryText}>Send order request</Text></TouchableOpacity>{status?<Text style={s.notice}>{status}</Text>:null}</ScrollView></SafeAreaView>}
function Label({text}:{text:string}){return <Text style={s.label}>{text}</Text>};const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},page:{padding:20,paddingBottom:40},back:{color:colors.terra,fontWeight:"800",marginTop:10},kicker:{marginTop:32,color:colors.sage,fontSize:10,fontWeight:"800",letterSpacing:1.5},title:{fontSize:34,lineHeight:38,fontWeight:"700",letterSpacing:-1.4,color:colors.cocoa,marginTop:8},body:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8,marginBottom:12},label:{fontSize:10,fontWeight:"800",color:colors.cocoa2,marginTop:14,marginBottom:5},input:{borderWidth:1,borderColor:colors.line,borderRadius:11,backgroundColor:colors.paper,padding:12,color:colors.cocoa},primary:{marginTop:20,backgroundColor:colors.terra,borderRadius:radii.pill,padding:15,alignItems:"center"},primaryText:{color:colors.white,fontWeight:"800"},notice:{marginTop:12,padding:10,backgroundColor:colors.butter,borderRadius:10,color:colors.cocoa2,fontSize:11}})
